name: Justin Cruz 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
body {
    background-image: url("https://i.gifer.com/myz.gif");
    background-repeat: no-repeat;
    background-position: right top;
    margin-right: 200px;
    background-attachment: fixed;
    margin: 60px auto;
    width: 70%;
}
